server:
  port: 9101
eureka:
  client:
    service-url:
      defaultZone: http://192.168.25.128:8761/eureka/
spring:
  application:
    name: track-1
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://192.168.25.128:9411/
    sender:
      type: rabbit
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest