server:
  port: 7001
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/spring_zcy/corejava.git
          search-paths: config-repo
          username: 457540867@qq.com
          password: wszcy199503ns