server:
  port: 7001
spring:
  application:
    name: config-server
eureka:
  client:
    register-with-eureka: false # 不向注册中心注册自己
    #retch-registry: false # 注册中心的职责就是维护服务，不需要去检索服务
    service-url:
      defaultZone: http://localhost:8761/eureka/
