spring:
  cloud:
    stream:
      bindings:
        output:
          producer:
            partitionKeyExpression: payload
            partitionCount: 2
          destination: myMessage
          content-type: application/json
          group: stream-hello
server:
  port: 8082