spring:
  profiles:
    active: ${profile.active}
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    publisher-confirms: true
    listener:
      simple:
        acknowledge-mode: manual # 手动应答
        # NONE 自动应答
        # AUTO
          # 1.没有异常，自动ACK
          # 2.抛出ImmediateAcknowledgeAmqpException异常时，消费者会发送 ACK
          # 3.抛出AmqpRejectAndDontRequeueException异常时，消息被拒绝,不重新入队
          # 4.其他的异常，消息被拒绝，重新入队
  redis:
    #sentinel:
      #master: mymaster
      #nodes: 192.168.25.128:26379,192.168.25.128:26380,192.168.25.128:26381
    password: 1234
    port: 6379
    host: localhost
#logging:
  #config: classpath:logback-spring.xml
  datasource:
    url: jdbc:mysql://localhost:3306/spring?allowMultiQueries=true&serverTimezone=UTC&useUnicode=true&useSSL=false&&zeroDateTimeBehavior=convertToNull&useOldAliasMetadataBehavior=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml

#server:
#  tomcat:
# 默认200
#    max-threads: 2000
xiaoxiao:
  hello:
    format:
      info:
        sex: '美女'
        age: 18
management:
  endpoints:
    web:
      exposure:
        include: '*'
#nacos:
  #config:
    #server-addr: localhost:8848