spring:
  profiles:
    active: ${profile.active}
    #rabbitmq:
    #host: localhost
    #port: 5672
    #username: guest
    #password: guest
    #publisher-confirms: true
      #listener:
      #simple:
      #acknowledge-mode: manual # 手动应答
        # NONE 自动应答
        # AUTO
          # 1.没有异常，自动ACK
          # 2.抛出ImmediateAcknowledgeAmqpException异常时，消费者会发送 ACK
          # 3.抛出AmqpRejectAndDontRequeueException异常时，消息被拒绝,不重新入队
          # 4.其他的异常，消息被拒绝，重新入队
  redis:
    #sentinel:
      #master: mymaster
      #nodes: 192.168.25.128:26379,192.168.25.128:26380,192.168.25.128:26381
    password:
    port: 6379
    host: localhost
#logging:
  #config: classpath:logback-spring.xml
  #--------------------------- 多数据源2配置 ---------------------------#
  #autoconfigure:
  #  exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  #datasource:
  #  type: com.zaxxer.hikari.HikariDataSource
  #  db1:
  #    jdbc-url: jdbc:mysql://localhost:3306/spring?allowMultiQueries=true&serverTimezone=UTC&useUnicode=true&useSSL=false&&zeroDateTimeBehavior=convertToNull&useOldAliasMetadataBehavior=true
  #    username: root
  #    password: 1234
  #    driver-class-name: com.mysql.cj.jdbc.Driver
  #  db2:
  #    jdbc-url: jdbc:mysql://localhost:3306/spring_1?allowMultiQueries=true&serverTimezone=UTC&useUnicode=true&useSSL=false&&zeroDateTimeBehavior=convertToNull&useOldAliasMetadataBehavior=true
  #    username: root
  #    password: 1234
  #    driver-class-name: com.mysql.cj.jdbc.Driver
  #    enabled: true
  #--------------------------- 多数据源2配置 ---------------------------#
  datasource:
    dynamic:
      primary: db1
      datasource:
        db1:
          url: jdbc:mysql://localhost:3306/spring?allowMultiQueries=true&serverTimezone=UTC&useUnicode=true&useSSL=false&&zeroDateTimeBehavior=convertToNull&useOldAliasMetadataBehavior=true
          username: root
          password: 1234
          driver-class-name: com.mysql.cj.jdbc.Driver
        db2:
          url: jdbc:mysql://localhost:3306/spring_1?allowMultiQueries=true&serverTimezone=UTC&useUnicode=true&useSSL=false&&zeroDateTimeBehavior=convertToNull&useOldAliasMetadataBehavior=true
          username: root
          password: 1234
          driver-class-name: com.mysql.cj.jdbc.Driver
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  # mybatis日志打印格式
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#server:
#  tomcat:
# 默认200
#    max-threads: 2000
xiaoxiao:
  hello:
    format:
      info:
        sex: '美女'
        age: 18
management:
  endpoints:
    web:
      exposure:
        include: '*'
#nacos:
  #config:
    #server-addr: localhost:8848