spring:
  application:
    name: track-1
  sleuth:
    sampler:
      percentage: 1.0
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
server:
  port: 9101
eureka:
  client:
    service-url:
      defaultZone: http://192.168.25.128:8761/eureka/