server:
  port: 9001
spring:
  application:
    name: feign-consumer
eureka:
  client:
    service-url:
      defaultZone: http://192.168.25.128:8761/eureka/
feign:
  hystrix:
    enabled: true